#############################################################################
# Makefile for building: Couleuvre-MNIST
# Generated by qmake (3.1) (Qt 5.9.2)
# Project:  ../Couleuvre-MNIST/Couleuvre-MNIST.pro
# Template: app
# Command: /home/manu/Qt/5.9.2/gcc_64/bin/qmake -o Makefile ../Couleuvre-MNIST/Couleuvre-MNIST.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++1y -Wall -W -fPIC $(DEFINES)
INCPATH       = -I../Couleuvre-MNIST -I.
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Couleuvre-MNIST1.0.0
DISTDIR = /home/manu/Documents/build-Couleuvre-MNIST-Desktop-Debug/.tmp/Couleuvre-MNIST1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Couleuvre-MNIST/sources/functions.cpp \
		../Couleuvre-MNIST/sources/main.cpp \
		../Couleuvre-MNIST/sources/mnist_reader.cpp \
		../Couleuvre-MNIST/sources/neuralnetwork.cpp \
		../Couleuvre-MNIST/sources/neuronlayer.cpp \
		../Couleuvre-MNIST/sources/teacher.cpp 
OBJECTS       = functions.o \
		main.o \
		mnist_reader.o \
		neuralnetwork.o \
		neuronlayer.o \
		teacher.o
DIST          = ../Couleuvre-MNIST/MNIST/t10k-images.idx3-ubyte \
		../Couleuvre-MNIST/MNIST/t10k-labels.idx1-ubyte \
		../Couleuvre-MNIST/MNIST/train-images.idx3-ubyte \
		../Couleuvre-MNIST/MNIST/train-labels.idx1-ubyte \
		../Couleuvre-MNIST/Couleuvre-MNIST.pro headers/CSVFile.h \
		headers/functions.hpp \
		headers/mnist_reader.h \
		headers/neuralnetwork.hpp \
		headers/neuronlayer.hpp \
		headers/teacher.hpp ../Couleuvre-MNIST/sources/functions.cpp \
		../Couleuvre-MNIST/sources/main.cpp \
		../Couleuvre-MNIST/sources/mnist_reader.cpp \
		../Couleuvre-MNIST/sources/neuralnetwork.cpp \
		../Couleuvre-MNIST/sources/neuronlayer.cpp \
                ../Couleuvre-MNIST/sources/teacher.cpp
DESTDIR       = 
TARGET        = Couleuvre-MNIST


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 	../Couleuvre-MNIST/Couleuvre-MNIST.pro


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

functions.o: ../Couleuvre-MNIST/sources/functions.cpp ../Couleuvre-MNIST/headers/functions.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functions.o ../Couleuvre-MNIST/sources/functions.cpp

main.o: ../Couleuvre-MNIST/sources/main.cpp ../Couleuvre-MNIST/headers/neuronlayer.hpp \
		../Couleuvre-MNIST/headers/neuralnetwork.hpp \
		../Couleuvre-MNIST/headers/neuralnetwork.inl \
		../Couleuvre-MNIST/headers/functions.hpp \
		../Couleuvre-MNIST/headers/teacher.hpp \
		../Couleuvre-MNIST/headers/mnist_reader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Couleuvre-MNIST/sources/main.cpp

mnist_reader.o: ../Couleuvre-MNIST/sources/mnist_reader.cpp ../Couleuvre-MNIST/headers/mnist_reader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mnist_reader.o ../Couleuvre-MNIST/sources/mnist_reader.cpp

neuralnetwork.o: ../Couleuvre-MNIST/sources/neuralnetwork.cpp ../Couleuvre-MNIST/headers/neuralnetwork.hpp \
		../Couleuvre-MNIST/headers/neuronlayer.hpp \
		../Couleuvre-MNIST/headers/neuralnetwork.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuralnetwork.o ../Couleuvre-MNIST/sources/neuralnetwork.cpp

neuronlayer.o: ../Couleuvre-MNIST/sources/neuronlayer.cpp ../Couleuvre-MNIST/headers/neuronlayer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuronlayer.o ../Couleuvre-MNIST/sources/neuronlayer.cpp

teacher.o: ../Couleuvre-MNIST/sources/teacher.cpp ../Couleuvre-MNIST/headers/teacher.hpp \
		../Couleuvre-MNIST/headers/neuralnetwork.hpp \
		../Couleuvre-MNIST/headers/neuronlayer.hpp \
		../Couleuvre-MNIST/headers/neuralnetwork.inl \
		../Couleuvre-MNIST/headers/functions.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o teacher.o ../Couleuvre-MNIST/sources/teacher.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

